"""
Problem 45: Triangular, pentagonal and hexagonal
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


def main():
    upper = 10000
    brute(upper=upper)
    

def clever():
    '''
    https://blog.dreamshire.com/project-euler-45-solution/

    Should solve the diophantine equation for 
    1/2 n(3n - 1) = 1/2 m(m+1)
    -> (6n - 1)^2 - 3(2m + 1)^2 = -2
    -> 36n^2 - 48m^2 -12n + 24m
    '''
    p = 165
    h = 143
    h = 84*p + 97*h - 38

    return h * (2*h - 1)

def brute(upper):
    for i in range(1, upper):
        t = tri(i)
        for j in range(1, upper):
            p = pen(j)
            for k in range(1, upper):
                h = hexa(k)
                if t == p == h:
                    print(i, j, k)
                    break


def tri(num):
    return num * (num + 1) / 2

def pen(num):
    return num * (3 * num - 1) / 2

def hexa(num):
    return num * (2 * num - 1)


if __name__ == '__main__':
    main()